### PR TITLE
ghostscript: fix i386 build. fix tiger build with gcc16.

### PR DESCRIPTION
**Pull request by alex-free**
I believe the gcc16 issue would impact all os versions as this occurs when using macports libiconv headers rather then system libiconv.

The i386 issue is old GCC4 versions don't have immintrin.h, this is an intel specific thing for SIMD like SSE2 (which we can actually use here as core solo/duo support up to SSE3).

### CODE REVIEW

File: print/ghostscript/Portfile [hunk 1]
```diff
@@ -105,6 +105,18 @@ depends_run-append \
...
+# matching_tag_mask.h:15:23: error: immintrin.h: No such file or directory
+if {${configure.build_arch} eq "i386"} {
+    compiler.blacklist *gcc-4.*
+}
+
+# When linking macports libiconv:
+# gdevopvp.c:1685:39: error: passing argument 2 of 'libiconv' from incompatible
+# pointer type [-Wincompatible-pointer-types] 
+if {[string match "macports-gcc-*" ${configure.compiler}]} {
+    configure.cflags-append "-Wno-error=incompatible-pointer-types"
```
Comment (barracuda156) [inline print/ghostscript/Portfile]: Why does this need to be quoted?

File: print/ghostscript/Portfile [hunk 2]
```diff
@@ -105,6 +105,18 @@ depends_run-append \
 compiler.c_standard 1999
 configure.cflags-append -std=gnu99
 
+# matching_tag_mask.h:15:23: error: immintrin.h: No such file or directory
+if {${configure.build_arch} eq "i386"} {
```
Comment (barracuda156) [inline print/ghostscript/Portfile]: Does this work for x86_64 though?

**Comment by barracuda156** [comment]
@alex-free Could you parse ports for 10.5-10.6 ppc in your current infrastructure? This stream of imports from MacPorts solely for the sake of Tiger increases indexing burden for everyone else (in addition to increased maintenance burden for me).

File: print/ghostscript/Portfile (hunk 2 above)
Comment (alex-free) [reply print/ghostscript/Portfile]: It would have the same issue on i.e. x86_64 snow leopard. Would platform i386 be best?

File: print/ghostscript/Portfile (hunk 1 above)
Comment (alex-free) [reply print/ghostscript/Portfile]: will change, not sure why my file of common macports conditionals had this quoted.

File: print/ghostscript/Portfile (hunk 2 above)
Comment (barracuda156) [reply print/ghostscript/Portfile]: Yeah, I think so.

Comment (barracuda156) [reply print/ghostscript/Portfile]: Hold on, that would unnecessarily include Rosetta.

Let’s keep `configure.build_arch` but add x86_64.

**Comment by alex-free** [comment]
> @alex-free Could you parse ports for 10.5-10.6 ppc in your current infrastructure? This stream of imports from MacPorts solely for the sake of Tiger increases indexing burden for everyone else (in addition to increased maintenance burden for me).

Like provide portindexes? That's just a matter of editing https://github.com/alex-free/tigerports-infrastructure/blob/0439e0c5f385ac94529a46f606d5cf43090606fc/jobs/mprsyncup#L78 . This is how I get around needing to portindex on local hardware (I offload it to the server like macports)

File: print/ghostscript/Portfile (hunk 2 above)
Comment (alex-free) [reply print/ghostscript/Portfile]: sure

**Comment by alex-free** [comment]
Also I'll try to help maintain the fixes I submit, I'm going to create a list to keep track of them on tigerports.com (and upstream status when applicable).

**Comment by alex-free** [comment]
hold up on this, I'm going to change it

**Comment by alex-free** [comment]
Ok good to go.

**Comment by alex-free** [comment]
@barracuda156 can we merge this here too?

File: print/ghostscript/Portfile [hunk 3]
```diff
@@ -105,6 +105,19 @@ depends_run-append \
 compiler.c_standard 1999
 configure.cflags-append -std=gnu99
 
+# Older gcc 4 does not provide the header.
+# matching_tag_mask.h:15:23: error: immintrin.h: No such file or directory
+if {${configure.build_arch} eq "i386" || ${configure.build_arch} eq "x86_64"} {
```
Comment (barracuda156) [inline print/ghostscript/Portfile:110]:
```
if {${configure.build_arch} in [list i386 x86_64]} {
```

P. S. This (usage of `${configure.build_arch}`) probably won’t work with universal builds, but given that universal builds involving ppc are largely broken anyway, I don’t really care.

File: print/ghostscript/Portfile [hunk 4]
```diff
@@ -105,6 +105,19 @@ depends_run-append \
...
+    compiler.blacklist *gcc-4.*
+}
+
+# When including macports libiconv:
+# gdevopvp.c:1685:39: error: passing argument 2 of 'libiconv' from incompatible
+# pointer type [-Wincompatible-pointer-types] 
+if {[string match macports-gcc-* ${configure.compiler}]} {
```
Comment (barracuda156) [inline print/ghostscript/Portfile]: This needs verification on 10.5/10.6.

**Review by barracuda156 — CHANGES_REQUESTED** [review]
I will check on 10.6 when I have time (will try doing it soon), but please change arch condition here.

File: print/ghostscript/Portfile (hunk 4 above)
Comment (alex-free) [reply print/ghostscript/Portfile]: Good idea, it could be how macports libiconv itself is interacting with system headers. I'm going to set up newer OS installs I just don't want to be stretched too thin.

Comment (barracuda156) [reply print/ghostscript/Portfile]: @alex-free I confirmed successful build on 10.6 with gcc-16 without adding this flag (or any other changes in portfile). So this should not be added unconditionally, it is a Tiger-specific issue.

**Comment by alex-free** [comment]
If there’s better arch detection that preserves Rosetta, let me know

File: print/ghostscript/Portfile [hunk 5]
```diff
@@ -0,0 +1,255 @@
+# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
+
+PortSystem          1.0
+PortGroup           muniversal 1.0
+
+name                ghostscript
+version             10.07.1
```
Comment (barracuda156) [inline print/ghostscript/Portfile:7]: This needs to use the current version: https://github.com/macports/macports-ports/blob/3e41875ed2aa31f40f59edbb593ee11dffa61f51/print/ghostscript/Portfile

**Review by barracuda156 — CHANGES_REQUESTED** [review]

**Comment by barracuda156** [comment]
@alex-free I have imported the port in its current ver: https://github.com/macos-powerpc/powerpc-ports/commit/9b94740b8e6d3958d4c0d7b4c45b2213e0c6e71f

**Comment by alex-free** [comment]
> @alex-free I have imported the port in its current ver: https://github.com/macos-powerpc/powerpc-ports/commit/9b94740b8e6d3958d4c0d7b4c45b2213e0c6e71f

I'll redo the patches thanks

**Comment by alex-free** [comment]
redid new pull request for imported ver
