### ISSUE TITLE
vlc2 fails to configure on Leo

### ISSUE THREAD

**Issue by Randrianasulu** [macos-powerpc/powerpc-ports#129]
```
:info:configure checking for libavcodec >= 53.34.0 libavutil >= 51.22.0... yes
:info:configure configure: error: libavutil versions 57 and later are not supported.
:info:configure Command failed:  cd "/opt/local/var/macports/build/VLC2-dba9a517/work/vlc-2.2.8" &&
 ./configure --prefix=/opt/local/libexec/vlc2 --bindir=/opt/local/bin --disable-atmo --disable-debu
g --disable-dbus --disable-gnomevfs --disable-growl --disable-macosx-vlc-app --disable-notify --dis
able-update-check --enable-gnutls --enable-lua --with-contrib=/opt/local/var/macports/build/VLC2-db
a9a517/work/vlc-2.2.8/contrib --disable-freerdp --disable-macosx-eyetv --disable-macosx-qtkit --dis
able-opencv --enable-realrtsp --disable-smbclient --enable-dvdnav --enable-dvdread --enable-sftp --
enable-vcdx --disable-shout --enable-dvbpsi --enable-mkv --enable-mod --enable-mpc --enable-mux_ogg
 --enable-ogg --disable-fluidsynth --disable-gst-decode --disable-quicktime --enable-a52 --enable-a
vcodec --enable-avformat --enable-dca --enable-faad --enable-flac --enable-libass --enable-live555
--enable-mad --enable-ogg --enable-opus --enable-png --enable-postproc --enable-schroedinger --enab
le-speex --enable-swscale --enable-theora --enable-twolame --enable-vorbis --enable-vpx --enable-x2
64 --enable-x265 --disable-caca --disable-svg --disable-svgdec --enable-xcb --disable-xvideo --enab
le-fontconfig --enable-freetype --enable-fribidi --enable-sdl --enable-sdl-image --with-x --disable
-chromaprint --disable-jack --disable-pulse --enable-samplerate --disable-macosx --disable-macosx-d
ialog-provider --enable-qt --disable-skins2 --disable-vnc --enable-ncurses --disable-goom --enable-
bonjour --enable-upnp --disable-screen
:info:configure Exit code: 1
:error:configure Failed to configure VLC2: consult /opt/local/var/macports/build/VLC2-dba9a517/work
/vlc-2.2.8/config.log
```

**Comment by barracuda156** [comment]
@Randrianasulu That’s because ffmpeg was updated, and old VLC does not like it. Do we even need this port for anything? I was thinking to remove it, since it is wildly outdated and has little utility over alternatives. (And while it has a “GUI”, the actual playback is still passed to X11, Qt only handles menus.)

There is a modern VLC as VLC-X11 port, but IMO even that is redundant, since there are better multimedia players available: qmplay2, mpv, mplayer.

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 19:48 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4587395700>
>
> @Randrianasulu <https://github.com/Randrianasulu> That’s because ffmpeg
> was updated, and old VLC does not like it. Do we even need this port for
> anything? I was thinking to remove it, since it is wildly outdated and has
> little utility over alternatives. (And while it has a “GUI”, the actual
> playback is still passed to X11, Qt only handles menus.)
>
> There is a modern VLC as VLC-X11 port, but IMO even that is redundant,
> since there are better multimedia players available: qmplay2, mpv, mplayer.
>

I was mostly thinking about screen/webcam capture part of it.

But may be this feature does not even work in osx in vlc2 ? hard to say
without trying

**Comment by barracuda156** [comment]
> I was mostly thinking about screen/webcam capture part of it.
> But may be this feature does not even work in osx in vlc2 ? hard to say without trying

No idea, but perhaps VLC-X11 can do that as well (assuming VLC2 can)?

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 19:58 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4587418964>
>
> I was mostly thinking about screen/webcam capture part of it.
> But may be this feature does not even work in osx in vlc2 ? hard to say
> without trying
>
> No idea, but perhaps VLC-X11 can do that as well (assuming VLC2 can)?
>

I'll try vlc-x11 next (just 'sudo port install vlc' tried to install vlc2
on Leo )

currently building transmission-x11

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 20:02 Andrew Randrianasulu ***@***.***>:

>
>
> вс, 31 мая 2026 г., 19:58 Sergey Fedorov ***@***.***>:
>
>> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
>> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4587418964>
>>
>> I was mostly thinking about screen/webcam capture part of it.
>> But may be this feature does not even work in osx in vlc2 ? hard to say
>> without trying
>>
>> No idea, but perhaps VLC-X11 can do that as well (assuming VLC2 can)?
>>
>
> I'll try vlc-x11 next (just 'sudo port install vlc' tried to install vlc2
> on Leo )
>
> currently building transmission-x11
>

Error: Failed to configure VLC-X11: ffmpeg7 must be installed with +x11.
Error: See
/opt/local/var/macports/logs/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_multimedia_VLC-X11/VLC-X11/main.log
for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe
there is a bug.
Error: Processing of port VLC-X11 failed
power-mac-g5-user-usr:~ andrewrandrianasulu$ sudo port install ffmpeg7 +x11
--->  Upgrading already installed dependencies of ffmpeg7
--->  Computing dependencies for ffmpeg7
                       Error: Can't install libsdl2-x11 because conflicting
ports are active: libsdl2-cocoa               Error: Follow
https://guide.macports.org/#project.tickets if you believe there is a bug.
         Error: Processing of port ffmpeg7 failed

I guess libsd2-cocoa installed as mpv dependency (same conflict seem to
prevent gimp2 from building)

**Comment by barracuda156** [comment]
Well, current handling of +x11 is a bit of a mess, for historical reasons and lack of time to sort it out. Do this:
```
sudo port clean giflib zvbi ffmpeg7
sudo port -f deactivate libsdl2-cocoa
sudo port -v -N install libsdl2-x11
sudo port -v -N install ffmpeg7 +x11
```

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 20:51 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4587556174>
>
> Well, current handling of +x11 is a bit of a mess, for historical reasons
> and lack of time to sort it out. Do this:
>
> sudo port clean giflib zvbi ffmpeg7
> sudo port -f deactivate libsdl2-cocoa
> sudo port -v -N install libsdl2-x11
> sudo port -v -N install ffmpeg7 +x11
>
>
sadly after deactivating sdl2-cocoa and ffmpeg (8.*) I still get err from
vlc-x11 on Leo:


:info:build     mv -f $depbase.Tpo $depbase.Plo
:info:build darwin/netconf.c: In function 'vlc_getProxyUrl':
:info:build darwin/netconf.c:49:5: error:
'CFNetworkCopySystemProxySettings' is unavailable
:info:build    49 |     CFDictionaryRef dicRef =
CFNetworkCopySystemProxySettings();
:info:build       |     ^~~~~~~~~~~~~~~
:info:build In file included from
/System/Library/Frameworks/CoreServices.framework/Frameworks/CFNe
twork.framework/Headers/CFNetwork.h:63,
:info:build                  from
/System/Library/Frameworks/CoreServices.framework/Headers/CoreSer
vices.h:37,
:info:build                  from darwin/netconf.c:37:
:info:build
/System/Library/Frameworks/CoreServices.framework/Frameworks/CFNetwork.framework/Header
s/CFProxySupport.h:411:1: note: declared here
:info:build   411 | CFNetworkCopySystemProxySettings( void )
 __OSX_AVAILABLE_STARTING(__MAC_NA,__IPHONE_2_0);
:info:build       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build darwin/netconf.c:52:13: error: 'kCFNetworkProxiesHTTPProxy' is
unavailable
:info:build    52 |             dicRef, (const
void*)kCFNetworkProxiesHTTPProxy);
:info:build       |             ^~~~~~
:info:build
/System/Library/Frameworks/CoreServices.framework/Frameworks/CFNetwork.framework/Header
s/CFProxySupport.h:437:30: note: declared here
:info:build   437 | CFN_EXPORT const CFStringRef
kCFNetworkProxiesHTTPProxy                 __OSX_A
VAILABLE_STARTING(__MAC_NA,__IPHONE_2_0);
:info:build       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build darwin/netconf.c:54:13: error: 'kCFNetworkProxiesHTTPPort' is
unavailable
:info:build    54 |             dicRef, (const
void*)kCFNetworkProxiesHTTPPort);
:info:build       |             ^~~~~~
:info:build
/System/Library/Frameworks/CoreServices.framework/Frameworks/CFNetwork.framework/Header

{snip}

**Comment by barracuda156** [comment]
`kCFNetworkProxiesHTTPProxy` is 10.6+: https://developer.apple.com/documentation/cfnetwork/kcfnetworkproxieshttpproxy

I guess nobody built VLC on 10.5 lol

Looks like it was broken by https://github.com/videolan/vlc/commit/b062c14b11a1f2dc7df560fd77f4310995d20a6c (which instead of properly fixing macOS code just deleted it in favor of what was iOS code).
Maybe this patch will fix it: https://github.com/macos-powerpc/powerpc-ports/blob/a20e2c997dce30d49fe944c163ac6817009feaa7/multimedia/VLC2/files/patch-SystemConfiguration.diff

**Comment by barracuda156** [comment]
See: https://github.com/macos-powerpc/powerpc-ports/blob/a20e2c997dce30d49fe944c163ac6817009feaa7/multimedia/VLC2/Portfile#L228-L234

**Comment by barracuda156** [comment]
Copilot suggests modifying the fallback:
```
#else
#include <SystemConfiguration/SystemConfiguration.h>

char *vlc_getProxyUrl(const char *url)
{
    VLC_UNUSED(url);

    char *proxy_url = NULL;
    CFDictionaryRef proxies = SCDynamicStoreCopyProxies(NULL);

    if (proxies) {
        // Is HTTP proxy enabled?
        CFNumberRef cfn_httpProxyOn =
            (CFNumberRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPEnable);

        int i_httpProxyOn = 0;
        if (cfn_httpProxyOn)
            CFNumberGetValue(cfn_httpProxyOn, kCFNumberIntType, &i_httpProxyOn);

        if (i_httpProxyOn == 1) {
            // Get hostname
            CFStringRef httpProxy =
                (CFStringRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPProxy);

            // Get port
            CFNumberRef cfn_httpProxyPort =
                (CFNumberRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPPort);

            int i_httpProxyPort = 0;
            if (cfn_httpProxyPort)
                CFNumberGetValue(cfn_httpProxyPort, kCFNumberIntType, &i_httpProxyPort);

            if (httpProxy) {
                char host_buffer[4096];
                if (CFStringGetCString(httpProxy, host_buffer, sizeof(host_buffer), kCFStringEncodingUTF8)) {
                    if (i_httpProxyPort > 0)
                        asprintf(&proxy_url, "http://%s:%d", host_buffer, i_httpProxyPort);
                    else
                        asprintf(&proxy_url, "http://%s", host_buffer);
                }
            }
        }

        CFRelease(proxies);  // Only release what you own
    }

    return proxy_url;
}
#endif
```

I don’t know what this is used for and how to test it. You can disable auto cleanup in `macports.conf`, so that if you need to rebuild VLC with modified code, you can just delete destroot folder, modify state file (delete targets following configure), change whatever code needed, then run `sudo port -v -n -s upgrade --force VLC-X11`.

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 23:44 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4588031228>
>
> Copilot suggests modifying the fallback:
>
> #else
> #include <SystemConfiguration/SystemConfiguration.h>
>
> char *vlc_getProxyUrl(const char *url)
> {
>     VLC_UNUSED(url);
>
>     char *proxy_url = NULL;
>     CFDictionaryRef proxies = SCDynamicStoreCopyProxies(NULL);
>
>     if (proxies) {
>         // Is HTTP proxy enabled?
>         CFNumberRef cfn_httpProxyOn =
>             (CFNumberRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPEnable);
>
>         int i_httpProxyOn = 0;
>         if (cfn_httpProxyOn)
>             CFNumberGetValue(cfn_httpProxyOn, kCFNumberIntType, &i_httpProxyOn);
>
>         if (i_httpProxyOn == 1) {
>             // Get hostname
>             CFStringRef httpProxy =
>                 (CFStringRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPProxy);
>
>             // Get port
>             CFNumberRef cfn_httpProxyPort =
>                 (CFNumberRef)CFDictionaryGetValue(proxies, kSCPropNetProxiesHTTPPort);
>
>             int i_httpProxyPort = 0;
>             if (cfn_httpProxyPort)
>                 CFNumberGetValue(cfn_httpProxyPort, kCFNumberIntType, &i_httpProxyPort);
>
>             if (httpProxy) {
>                 char host_buffer[4096];
>                 if (CFStringGetCString(httpProxy, host_buffer, sizeof(host_buffer), kCFStringEncodingUTF8)) {
>                     if (i_httpProxyPort > 0)
>                         asprintf(&proxy_url, "http://%s:%d", host_buffer, i_httpProxyPort);
>                     else
>                         asprintf(&proxy_url, "http://%s", host_buffer);
>                 }
>             }
>         }
>
>         CFRelease(proxies);  // Only release what you own
>     }
>
>     return proxy_url;
> }
> #endif
>
> I don’t know what this is used for and how to test it. You can disable
> auto cleanup in macports.conf, so that if you need to rebuild VLC with
> modified code, you can just delete destroot folder, modify state file
> (delete targets following configure), change whatever code needed, then run sudo
> port -v -n -s upgrade --force VLC-X11.
>

first patch you highlighted failed to apply to vlc-x11, second applied

now I think only audiotoolbox_midi.c error remain ?

May be just disabling building of this  file will help ? (on leopard)

**Comment by barracuda156** [comment]
Maybe try removing it from configure: https://github.com/videolan/vlc/blob/79128878ddb2c280bbb6c89c76a46b31a80ade1c/configure.ac#L4154-L4157
Or, better, add a configure option to control that.

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 00:26 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4588148225>
>
> Maybe try removing it from configure:
> https://github.com/videolan/vlc/blob/79128878ddb2c280bbb6c89c76a46b31a80ade1c/configure.ac#L4154-L4157
> Or, better, add a configure option to control that.
>

I just fixed it same way as in first patch - AudioComponent -> component

new err:

:info:build access/screen/mac.c:41:2: warning: #import is a deprecated GCC
extension [-Wdeprecated]
:info:build    41 | #import <QuartzCore/QuartzCore.h>
:info:build       |  ^~~~~~
:info:build access/screen/mac.c: In function 'screen_Capture':
:info:build access/screen/mac.c:181:11: error: assignment to 'CGImageRef'
{aka 'struct CGImage *'}
from 'int' makes pointer from integer without a cast [-Wint-conversion]
:info:build   181 |     image =
CGDisplayCreateImageForRect(p_data->display_id, capture_rect);
:info:build       |           ^
:info:build make[4]: *** [access/screen/mac.lo] Error 1
:info:build make[4]: *** Waiting for unfinished jobs....

**Comment by Randrianasulu** [comment]
[audiotoolbox_midi.c.txt](https://github.com/user-attachments/files/28444972/audiotoolbox_midi.c.txt)

modded audiotoolbo_midi.c file.

sorry for not diff, manipulating files via root where ports not in path a bit cumbersome

**Comment by barracuda156** [comment]
You could add `-Wno-error=int-conversion` (won’t fix the problem, but maybe it gonna work nevertheless) or check what older code was doing. If CoreGraphics in 10.5 does not have some API used here, the code rather be fixed.

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 00:49 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4588198932>
>
> You could add -Wno-error=int-conversion (won’t fix the problem, but maybe
> it gonna work nevertheless) or check what older code was doing. If
> CoreGraphics in 10.5 does not have some API used here, the code rather be
> fixed.
>


I shut it up like this:


    image = (CGImageRef* )CGDisplayCreateImageForRect(p_data->display_id,
capture_rect);

and in vlc-3.0.23-2/modules/audio_output/coreaudio_common.c

au_component = (Component* )AudioComponentFindNext(NULL, &desc);

but now I have

:info:build Undefined symbols for architecture ppc:
:info:build   "_CGDisplayCreateImageForRect", referenced from:
:info:build       _screen_Capture in mac.o
                       :info:build ld: symbol(s) not found for architecture
ppc

I googled this symbol and you need linking with CoreGraphics?

https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.10.sdk/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics.tbd

**Comment by Randrianasulu** [comment]
ah, I was wrong

https://groups.google.com/g/quartz-dev/c/PYXNg8bj5FU

"CGWindow APIs (10.5+) or CGDisplayCreateImageForRect() (10.6+)"

so this is 10.6 api and should work on your 10.6.8 but on 10.5 - without writing whole new block in this file (modules/acces/screen/mac.c ) it will not work ... sad.

**Comment by barracuda156** [comment]
That module was added in 0.8.0: https://github.com/videolan/vlc/commit/359a9bafcc9026aa095325087867fc2954f8a8b9
For sure there exists a version which works on 10.5.

**Comment by Matias314** [comment]
The last official release for 10.5 was [2.0.10](https://www.videolan.org/vlc/download-macosx.html).

**Comment by barracuda156** [comment]
I am pretty sure our VLC2 (2.2.8) builds on 10.5.8.

**Comment by Matias314** [comment]
Yeah it has definitely built before, I have a version in my repo. But it stopped building a few weeks or months ago.

**Comment by barracuda156** [comment]
> Yeah it has definitely built before, I have a version in my repo. But it stopped building a few weeks or months ago.

After ffmpeg update or earlier? The port itself did not change, so the only thing which could break are dependencies. If we want to keep the port, it should a) be switched to `ffmpeg4` and b) if some other dependency is incompatible now, just disable it (pretty much everything is optional in VLC). If no one makes a PR, I will probable just remove the port, since we have a much newer VLC.

**Comment by Randrianasulu** [comment]
https://code.videolan.org/videolan/vlc/-/commit/8ef6e5c761423d007c0d839e7870fd627283b20c

may be it broke for 10.5 at this commit?

**Comment by Randrianasulu** [comment]
configue.ac list this for enabling screen capture

--enable-screen

so I guess --disable-screen will disable it on 10.5, if revert of this Lion support in this module actually too hard?

**Comment by Randrianasulu** [comment]
> > Yeah it has definitely built before, I have a version in my repo. But it stopped building a few weeks or months ago.
> 
> After ffmpeg update or earlier? The port itself did not change, so the only thing which could break are dependencies. If we want to keep the port, it should a) be switched to `ffmpeg4` and b) if some other dependency is incompatible now, just disable it (pretty much everything is optional in VLC). If no one makes a PR, I will probable just remove the port, since we have a much newer VLC.

I think deleting patches you can reference later is not really good idea. Just put some stance saying it broken so ports system  will warn user like it was done  with rust ?

**Comment by barracuda156** [comment]
> configue.ac list this for enabling screen capture
> --enable-screen
> so I guess --disable-screen will disable it on 10.5, if revert of this Lion support in this module actually too hard?

I am fine with this.

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 16:04 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#129)
> <https://github.com/macos-powerpc/powerpc-ports/issues/129#issuecomment-4592840377>
>
> configue.ac list this for enabling screen capture
> --enable-screen
> so I guess --disable-screen will disable it on 10.5, if revert of this
> Lion support in this module actually too hard?
>
> I am fine with this.
>


Also, question:

how you create patches from already-patched by ports workdir? Just compare
your saved/symlinked working copy with folder set aside after auto patching?

**Comment by barracuda156** [comment]
> how you create patches from already-patched by ports workdir? Just compare your saved/symlinked working copy with folder set aside after auto patching?

Yeah, or use git to manage patches if there are a lot and/or changes are complex.
