### PR TITLE
toxcore: link with -latomic on 10.5

### PR DESCRIPTION
**Pull request by Matias314**
This fixes the build:
```
:info:build [ 90%] Linking CXX executable unit_TCP_client_test
:info:build /opt/local/bin/cmake -E cmake_link_script CMakeFiles/unit_TCP_client_test.dir/link.txt --verbose=ON
:info:build Undefined symbols for architecture ppc:
:info:build   "___atomic_fetch_add_8", referenced from:
:info:build       tox::test::FakeClock::advance(unsigned long long) in libsupport.a(fake_clock.cc.o)
:info:build   "___atomic_load_8", referenced from:
:info:build       tox::test::FakeClock::current_time_s() const in libsupport.a(fake_clock.cc.o)
:info:build       tox::test::FakeClock::current_time_ms() const in libsupport.a(fake_clock.cc.o)
:info:build ld: symbol(s) not found for architecture ppc
:info:build collect2: error: ld returned 1 exit status**
```

### CODE REVIEW

File: net/toxcore/Portfile [hunk 1]
```diff
@@ -53,6 +53,11 @@ if {[string match *clang* ${configure.compiler}]} {
                         -lomp
 }
 
+# __atomic_*
+if {${os.platform} eq "darwin" && ${os.major} < 10} {
```
Comment (barracuda156) [inline net/toxcore/Portfile]: TBH that’s weird how it worked on 10.6 (or why would I not add a flag into my own port), but anyway, condition should different. Like this: https://github.com/macos-powerpc/powerpc-ports/blob/caf9aa073984380c4cef84a016defe6591e51bd3/databases/tiledb/Portfile#L75

**Review by barracuda156 — CHANGES_REQUESTED** [review]

**Comment by Matias314** [comment]
Like this?

**Review by barracuda156 — APPROVED** [review]
