### PR TITLE
opencolorio: add legacysupport for 10.5 and include stdlib.h

### LINKED ISSUE #116: opencolorio build failure on 10.5: posix_memalign strikes again
```
/opt/local/var/macports/build/opencolorio-be5e4f59/work/OpenColorIO-2.5.1/src/OpenColorIO/Platform.cpp: In function 'void* OpenColorIO_v2_5::Platform::AlignedMalloc(size_t, size_t)':
/opt/local/var/macports/build/opencolorio-be5e4f59/work/OpenColorIO-2.5.1/src/OpenColorIO/Platform.cpp:189:10: error: 'posix_memalign' was not declared in this scope
  189 |     if (!posix_memalign(&memBlock, alignment, size)) return memBlock;
      |          ^~~~~~~~~~~~~~
```

Sadly adding LegacySupport PG has no effect, even though I can see `-isystem/opt/local/include/LegacySupport` being added to the cppflags.

### PR DESCRIPTION
**Pull request by Matias314**
Fixes macos-powerpc/powerpc-ports#116

### CODE REVIEW

File: graphics/opencolorio/files/0003-include-stdlib.patch [hunk 1]
```diff
@@ -0,0 +1,10 @@
+--- src/OpenColorIO/Platform.cpp.orig
++++ src/OpenColorIO/Platform.cpp
+@@ -11,6 +11,7 @@
+ #include <OpenColorIO/OpenColorIO.h>
+
+ #include "Platform.h"
++#include "stdlib.h"
```
Comment (barracuda156) [inline graphics/opencolorio/files/0003-include-stdlib.patch]: This should go together with `<strings.h>` below (or above with C++ headers), and as
```
#include <stdlib.h>
```
(`"` are used with local headers.)

**Review by barracuda156 — CHANGES_REQUESTED** [review]

File: graphics/opencolorio/files/0003-include-stdlib.patch (hunk 1 above)
Comment (Matias314) [reply graphics/opencolorio/files/0003-include-stdlib.patch]: Whoops, fixed

**Review by barracuda156 — APPROVED** [review]

**Comment by barracuda156** [comment]
@Matias314 Does the updated `ffmpeg` build on 10.5?

**Comment by Matias314** [comment]
Yep it built fine overnight.
