### ISSUE TITLE
basiliskii-gui fails to build on Leo (g++ 4.2 issue?)

### ISSUE THREAD

**Issue by Randrianasulu** [macos-powerpc/powerpc-ports#130]
```
:info:destroot /usr/bin/g++-4.2 -I/opt/local/var/macports/build/basiliskii-gui-cfe62ee9/work/macemu
-6393d14abf31b302d578d05da7e5ddbddd07ae45/BasiliskII/src/Unix/../include -I/opt/local/include -I../
MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -
DOS_darwin -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -arch ppc -I
/opt/local/include/SDL2 -D_THREAD_SAFE -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -c ether_
unix.cpp -o obj/ether_unix.o
:info:destroot ether_unix.cpp: In function ‘bool ether_init()’:
:info:destroot ether_unix.cpp:336: error: expected primary-expression before ‘.’ token
:info:destroot ether_unix.cpp:337: error: expected primary-expression before ‘.’ token
:info:destroot ether_unix.cpp:338: error: expected primary-expression before ‘.’ token
:info:destroot make: *** [obj/ether_unix.o] Error 1
```

technically not ppcport issue but I suspect  it new c++ code sneaking into old codebase again ....

**Comment by barracuda156** [comment]
I get a different error:
```
/usr/bin/g++-4.2 -I/opt/local/var/macports/build/basiliskii-gui-1592dce4/work/macemu-6393d14abf31b302d578d05da7e5ddbddd07ae45/BasiliskII/src/Unix/../include -I/opt/local/include -I../MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -arch ppc -I/opt/local/include/SDL2 -D_THREAD_SAFE -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -c ./../MacOSX/utils_macosx.mm -o obj/utils_macosx.o
./../MacOSX/utils_macosx.mm: In function ‘bool is_fullscreen_osx(SDL_Window*)’:
./../MacOSX/utils_macosx.mm:69: error: ‘NSWindowStyleMask’ does not name a type
./../MacOSX/utils_macosx.mm:70: error: ‘styleMask’ was not declared in this scope
./../MacOSX/utils_macosx.mm:70: error: ‘NSWindowStyleMaskFullScreen’ was not declared in this scope
make: *** [obj/utils_macosx.o] Error 1
```

**Comment by Randrianasulu** [comment]
вс, 31 мая 2026 г., 20:05 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#130)
> <https://github.com/macos-powerpc/powerpc-ports/issues/130#issuecomment-4587435720>
>
> I get a different error:
>
> /usr/bin/g++-4.2 -I/opt/local/var/macports/build/basiliskii-gui-1592dce4/work/macemu-6393d14abf31b302d578d05da7e5ddbddd07ae45/BasiliskII/src/Unix/../include -I/opt/local/include -I../MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -arch ppc -I/opt/local/include/SDL2 -D_THREAD_SAFE -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -c ./../MacOSX/utils_macosx.mm -o obj/utils_macosx.o
> ./../MacOSX/utils_macosx.mm: In function ‘bool is_fullscreen_osx(SDL_Window*)’:
> ./../MacOSX/utils_macosx.mm:69: error: ‘NSWindowStyleMask’ does not name a type
> ./../MacOSX/utils_macosx.mm:70: error: ‘styleMask’ was not declared in this scope
> ./../MacOSX/utils_macosx.mm:70: error: ‘NSWindowStyleMaskFullScreen’ was not declared in this scope
> make: *** [obj/utils_macosx.o] Error 1
>
>
yeah, this is probably why macports tracker requires full log - I looked at
it from very end

**Comment by barracuda156** [comment]
Oh lawd...
```
/usr/bin/gcc-4.2 -std=gnu99 -I/opt/local/var/macports/build/basiliskii-gui-1592dce4/work/macemu-6393d14abf31b302d578d05da7e5ddbddd07ae45/BasiliskII/src/Unix/../include -I/opt/local/include -I../MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -arch ppc -I/opt/local/include/SDL2 -D_THREAD_SAFE -mdynamic-no-pic -c ./../uae_cpu/build68k.c -o obj/build68k.o
/usr/bin/gcc-4.2 -std=gnu99 -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -Wl,-seg1addr,0x78048000 -o obj/build68k obj/build68k.o
obj/build68k <./../uae_cpu/table68k >cpudefs.cpp
/bin/sh: line 1:  4775 Segmentation fault      obj/build68k < ./../uae_cpu/table68k > cpudefs.cpp
make: *** [cpudefs.cpp] Error 139
```

**Comment by barracuda156** [comment]
And then:
```
/usr/bin/g++-4.2 -I/opt/local/var/macports/build/basiliskii-gui-1592dce4/work/macemu-6393d14abf31b302d578d05da7e5ddbddd07ae45/BasiliskII/src/Unix/../include -I/opt/local/include -I../MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -arch ppc -I/opt/local/include/SDL2 -D_THREAD_SAFE -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -c cpudefs.cpp -o obj/cpudefs.o
/usr/bin/g++-4.2 -L/opt/local/lib -Wl,-headerpad_max_install_names -arch ppc -Wl,-seg1addr,0x78048000 -o obj/gencpu obj/gencpu.o obj/readcpu.o obj/cpudefs.o
Undefined symbols for architecture ppc:
  "_defs68k", referenced from:
      _read_table68k in readcpu.o
  "_n_defs68k", referenced from:
      _read_table68k in readcpu.o
ld: symbol(s) not found for architecture ppc
collect2: ld returned 1 exit status
make: *** [obj/gencpu] Error 1
```
Looks like the build system is a total mess.

**Comment by barracuda156** [comment]
@Randrianasulu I did not try running it, but the build should be fixed.

**Comment by Randrianasulu** [comment]
> [@Randrianasulu](https://github.com/Randrianasulu) I did not try running it, but the build should be fixed.

GUI part starts and allow me to configure machine. Then B2 itself crashes early .. tried to disable cdrom/audio - still crash.

May be two libgcc_s dylibs linked to it  can be blamed? (gdb  BasiliskII prints crash somewhere at module loading)

**Comment by barracuda156** [comment]
Can you try adding `compiler.cxx_standard 2011` into portfile and rebuild the port?

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 16:00 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#130)
> <https://github.com/macos-powerpc/powerpc-ports/issues/130#issuecomment-4592809367>
>
> Can you try adding compiler.cxx_standard 2011 into portfile and rebuild
> the port?
>

I am trying but


--->  Fetching archive for basiliskii-gui

^C
^C

because

ping http://kemonomimi.nl
ping: unknown host http://kemonomimi.nl

from my corner of the world, suddenly.

**Comment by Matias314** [comment]
My webserver hung and I had to reboot it, apologies.

**Comment by Randrianasulu** [comment]
may be I put it into wrong part of portfile, but still crashes:

```
power-mac-g5-user-usr:src andrewrandrianasulu$ otool -L /opt/local/bin/BasiliskII
/opt/local/bin/BasiliskII:
        /opt/local/lib/libvdeplug.3.dylib (compatibility version 4.0.0, current version 4.1.0)
        /opt/local/lib/libSDL2-2.0.0.dylib (compatibility version 3201.0.0, current version 3201.10.0)
        /opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.33.0)
        /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 949.54.0)
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.19.0)
        /opt/local/lib/libgcc/libgcc_s.1.1.dylib (compatibility version 1.0.0, current version 1.1.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.7)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 227.0.0)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 677.26.0)
power-mac-g5-user-usr:src andrewrandrianasulu$ gdb /opt/local/bin/BasiliskII
GNU gdb 6.3.50-20050815 (Apple version gdb-967) (Tue Jul 14 02:15:14 UTC 2009)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "powerpc-apple-darwin"...Reading symbols for shared libraries ............. done

(gdb) r
Starting program: /opt/local/bin/BasiliskII
Reading symbols for shared libraries ++++++++++++............................................................................... done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x000b1e6c
0x8fe17f74 in __dyld__ZN16ImageLoaderMachO25doBindExternalRelocationsERKN11ImageLoader11LinkContextEb ()
(gdb)

```

**Comment by barracuda156** [comment]
`/opt/local/lib/libvdeplug.3.dylib` is from `vde2` port? Why it is used?
You can try `bt` in GDB to see where exactly it crashes.

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 18:13 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#130)
> <https://github.com/macos-powerpc/powerpc-ports/issues/130#issuecomment-4593924554>
>
> /opt/local/lib/libvdeplug.3.dylib is from vde2 port? Why it is used?
>

Well, I installed it for testing interVM networking (used this with some
success on Linux)


You can try bt in GDB to see where exactly it crashes.
>

(gdb) bt
#0  0x8fe17f74 in
__dyld__ZN16ImageLoaderMachO25doBindExternalRelocationsERKN11ImageLoader11LinkContextEb
()
#1  0x8fe18068 in
__dyld__ZN16ImageLoaderMachO6doBindERKN11ImageLoader11LinkContextEb ()
#2  0x8fe0dae0 in
__dyld__ZN11ImageLoader13recursiveBindERKNS_11LinkContextEb ()
#3  0x8fe11108 in
__dyld__ZN11ImageLoader4linkERKNS_11LinkContextEbbRKNS_10RPathChainE ()
#4  0x8fe05254 in __dyld__ZN4dyld4linkEP11ImageLoaderbRKNS0_10RPathChainE ()
#5  0x8fe08080 in __dyld__ZN4dyld5_mainEPK11mach_headermiPPKcS5_S5_ ()
#6  0x8fe01774 in __dyld__ZN13dyldbootstrap5startEPK11mach_headeriPPKcl ()
#7  0x8fe01048 in __dyld__dyld_start ()

**Comment by barracuda156** [comment]
Doesn’t suggest me anything lol
I would try doing the clean build without opportunistic dependencies (in fact it may be useful to disable everything optional first) and setting `compiler.cxx_standard 2011` (this has some up and downsides, but at least worth trying).

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 18:33 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#130)
> <https://github.com/macos-powerpc/powerpc-ports/issues/130#issuecomment-4594089051>
>
> Doesn’t suggest me anything lol
> I would try doing the clean build without opportunistic dependencies (in
> fact it may be useful to disable everything optional first) and setting compiler.cxx_standard
> 2011 (this has some up and downsides, but at least worth trying).
>

I tried to download upstream at

https://github.com/kanjitalk755/macemu

and top comment from may says

"
Author: kanjitalk755 ***@***.***>
                        Date:   Wed May 20 09:13:17 2026 +0900

    Merge pull request #302 from vasi/archpower

    Re-add support for running on a real PowerPC
"

;)

this is for sheepshaver, not B2 but hopefully it can be more buildable ..
in parts ...

**Comment by barracuda156** [comment]
I tried building from the master branch, but it fails on some targets-related mess: https://github.com/cebix/macemu/issues/293

**Comment by Randrianasulu** [comment]
пн, 1 июн. 2026 г., 19:03 Sergey Fedorov ***@***.***>:

> *barracuda156* left a comment (macos-powerpc/powerpc-ports#130)
> <https://github.com/macos-powerpc/powerpc-ports/issues/130#issuecomment-4594317344>
>
> I tried building from the master branch, but it fails on some
> targets-related mess: cebix/macemu#293
> <https://github.com/cebix/macemu/issues/293>
>

I tried different fork but run into different problem (Metal headers for
new macos breaking compilation on Leo ) and my issue was closed as not
planned :)

**Comment by barracuda156** [comment]
@Randrianasulu It is probably not too hard to trash Metal stuff, as long as the code was not rewritten completely.

**Comment by Randrianasulu** [comment]
Developer get it working on Tiger, by disabling sdl and using x11 (I think)

https://github.com/kanjitalk755/macemu/issues/303#issuecomment-4611903259

**Comment by barracuda156** [comment]
`strnlen` can be provided by `legacy-support`, though if it is the only missing thing, manually added code may be preferable.
I don’s think our SDL2 should cause crashes; AFAIK, it works. (It can cause crashes on modern systems though.)
But in any case, X11 is a valid option to go with.
