### ISSUE TITLE
Audacious-plugins fail to build on 10.5.8

### ISSUE THREAD

**Issue by Randrianasulu** [macos-powerpc/powerpc-ports#126]
```
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:157:8: error: 'AudioComponent' do
es not name a type; did you mean 'Component'?
:info:build   157 | static AudioComponent output_comp = nullptr;
:info:build       |        ^~~~~~~~~~~~~~
:info:build       |        Component
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc: In member function 'virtual bool
 CoreAudioPlugin::init()':
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:203:5: error: 'AudioComponentDesc
ription' was not declared in this scope; did you mean 'ComponentDescription'?
:info:build   203 |     AudioComponentDescription desc;
:info:build       |     ^~~~~~~~~~~~~~~~~~~~~~~~~
:info:build       |     ComponentDescription
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:204:5: error: 'desc' was not decl
ared in this scope
:info:build   204 |     desc.componentType = kAudioUnitType_Output;
:info:build       |     ^~~~
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:210:5: error: 'output_comp' was n
ot declared in this scope
:info:build   210 |     output_comp = AudioComponentFindNext (nullptr, & desc);
:info:build       |     ^~~~~~~~~~~
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:210:19: error: 'AudioComponentFin
dNext' was not declared in this scope
:info:build   210 |     output_comp = AudioComponentFindNext (nullptr, & desc);
:info:build       |                   ^~~~~~~~~~~~~~~~~~~~~~
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:217:20: error: 'AudioComponentIns
tanceNew' was not declared in this scope; did you mean 'badComponentInstance'?
:info:build   217 |     OSStatus err = AudioComponentInstanceNew (output_comp, & output_instance);
:info:build       |                    ^~~~~~~~~~~~~~~~~~~~~~~~~
:info:build       |                    badComponentInstance
:info:build ../audacious-plugins-4.5.1/src/coreaudio/coreaudio.cc:111:36: warning: format '%d' expe
cts argument of type 'int', but argument 2 has type 'OSStatus' {aka 'long int'} [-Wformat=]
:info:build   111 |     aud_ui_show_error (str_printf ("CoreAudio error: " __VA_ARGS__)); \

```

**Comment by barracuda156** [comment]
@Randrianasulu Something like https://github.com/macos-powerpc/powerpc-ports/commit/5357557de16fca680f4832b34a59cea8568ddd13 or https://github.com/macos-powerpc/powerpc-ports/blob/7b036b5c85b2c85d95c004d6847483d097482d43/audio/portaudio/files/patch-Restore-support-for-10.5.diff will probably fix it. I leave that to interested parties, since I don’t have dependencies for this port or time/cpu cycles to build them.

P. S. If you care to fix this, PR is welcome.

**Comment by Randrianasulu** [comment]
Sure .... (I am not big enjoyner of port system, too complicated for me).

Anyway, as long as pulseaudio working - may be just disable coreaudio and enable pulseuadio output in audacious-plugins on Leo?

I trink mr Rust will make my Dualcore busy for some time too ;)

**Comment by barracuda156** [comment]
> Anyway, as long as pulseaudio working - may be just disable coreaudio and enable pulseuadio output in audacious-plugins on Leo?

I don’t really like the idea, since it amounts to settling on a clearly suboptimal solution. (`portaudio` is okay since it uses CoreAudio internally, but `pulseaudio` is essentially a Linux thing.)
Having said that, if fixing CoreAudio proves problematic, that will be better than nothing.

> I trink mr Rust will make my Dualcore busy for some time too

I guess you mean `mrustc`? It will not build on 10.5, unless someone fixes it. (It may be not hard, but on ppc64 it is broken for another reason, so I cannot even get to the failure which happens on 10.5 ppc at linking.)
On 10.6 it builds and works, though do not expect it to be able to build arbitrary rust ports. In most cases it will fail: partly because it is not designed to support the whole of rust, partly because many rust apps are written carelessly, without any idea of portability and compatibility in mind. Some rust ports will build, often in earlier versions than what MacPorts has.

**Comment by Randrianasulu** [comment]
I did

sudo port update

twice, but it still builds 1.15 ?

sudo port search tigervnc also gives 1.14 and 1.15 even if potfile says 1.16.2 ?

**Comment by Randrianasulu** [comment]
err it was for another issue with tigervnc
