### ISSUE TITLE
Keychain-cpp (dependency of Abaddon) fails to build on 10.5

### ISSUE THREAD

**Issue by Matias314** [macos-powerpc/powerpc-ports#97]
```
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp: In function 'void {anonymous}::updateError(keychain::Error&, OSStatus)':
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp:84:19: error: 'errSecSuccess' was not declared in this scope; did you mean 'errSecNoSuchClass'?
:info:build    84 |     if (status == errSecSuccess) {
:info:build       |                   ^~~~~~~~~~~~~
:info:build       |                   errSecNoSuchClass
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp: In function 'OSStatus {anonymous}::modifyPassword(const std::string&, const std::string&, const std::string&)':
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp:129:19: error: 'errSecSuccess' was not declared in this scope; did you mean 'errSecNoSuchClass'?
:info:build   129 |     if (status == errSecSuccess) {
:info:build       |                   ^~~~~~~~~~~~~
:info:build       |                   errSecNoSuchClass
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp: In function 'void keychain::setPassword(const std::string&, const std::string&, const std::string&, const std::string&, Error&)':
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp:169:19: error: 'errSecSuccess' was not declared in this scope; did you mean 'errSecNoSuchClass'?
:info:build   169 |     if (status != errSecSuccess) {
:info:build       |                   ^~~~~~~~~~~~~
:info:build       |                   errSecNoSuchClass
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp: In function 'std::string keychain::getPassword(const std::string&, const std::string&, const std::string&, Error&)':
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp:193:19: error: 'errSecSuccess' was not declared in this scope; did you mean 'errSecNoSuchClass'?
:info:build   193 |     if (status != errSecSuccess) {
:info:build       |                   ^~~~~~~~~~~~~
:info:build       |                   errSecNoSuchClass
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp: In function 'void keychain::deletePassword(const std::string&, const std::string&, const std::string&, Error&)':
:info:build /opt/local/var/macports/build/keychain-cpp-5e5adc5d/work/keychain-1.2.1/src/keychain_mac.cpp:219:19: error: 'errSecSuccess' was not declared in this scope; did you mean 'errSecNoSuchClass'?
:info:build   219 |     if (status != errSecSuccess) {
:info:build       |                   ^~~~~~~~~~~~~
:info:build       |                   errSecNoSuchClass
:info:build make[2]: *** [CMakeFiles/keychain.dir/src/keychain_mac.cpp.o] Error 1
```

Maybe it should be removed as a default variant for 10.5? It builds & launches fine without it.

**Comment by barracuda156** [comment]
I am not sure why it is not defined, Apple claims it should: https://developer.apple.com/documentation/security/errsecsuccess

Does this fix the issue? https://github.com/macos-powerpc/powerpc-ports/blob/63aa8182623f5a5b2fa97dfe8ba4e33ea61763c8/graphics/wxgtk-3.2/files/patch-leopard.diff#L130-L135

I don’t particularly mind disabling it, but since `keychain-cpp` may turn up as a dependency somewhere else, makes sense to fix it.

**Comment by Matias314** [comment]
Haha wow yeah that fixes it. Great, thank you!
