### ISSUE TITLE
deadbeef fails to compile on 10.5

### ISSUE THREAD

**Issue by Randrianasulu** [macos-powerpc/powerpc-ports#143]
```
/opt/local/share/doc/deadbeef\" -DDDB_WARN_DEPRECATED=1 -c fileman.c  -fno-common -DPIC -o .libs/dd
b_gui_GTK3_la-fileman.o
:info:build fileman.c:25:10: fatal error: dispatch/dispatch.h: No such file or directory
:info:build    25 | #include <dispatch/dispatch.h>
:info:build       |          ^~~~~~~~~~~~~~~~~~~~~
:info:build compilation terminated.
:info:build make[3]: *** [ddb_gui_GTK3_la-fileman.lo] Error 1
:info:build make[3]: *** Waiting for unfinished jobs....
```

**Comment by barracuda156** [comment]
I guess I did not prohibit building it back then assuming dispatch may be implemented on 10.5. I will set platforms to 10.6+.
