### ISSUE TITLE
Squid build failure on 10.5:

### ISSUE THREAD

**Issue by Matias314** [macos-powerpc/powerpc-ports#140]
```
:info:build ext_session_acl.cc: In function 'void init_db()':
:info:build ext_session_acl.cc:144:59: error: 'O_DSYNC' was not declared in this scope; did you mean 'O_FSYNC'?
:info:build   144 |     db = tdb_open(db_path, 0, TDB_CLEAR_IF_FIRST, O_CREAT|O_DSYNC, 0666);
:info:build       |                                                           ^~~~~~~
:info:build       |                                                           O_FSYNC
:info:build make[5]: *** [ext_session_acl.o] Error 1
```
I vaguely recall being able to work around this by building it on another machine in the past, so  think it is a conflict of some kind?

PS: is there a way to deactivate all active ports and then reactivate all previously active ports that were deactivated?

**Comment by barracuda156** [comment]
That error happens in the code which is inside a macro, so I guess the build opportunistically picks `tdb` (or whatever it is): https://github.com/squid-cache/squid/blob/2c89b9b4054ad14ea191bc7cd35f969feba8df53/src/acl/external/session/ext_session_acl.cc#L144

**Comment by barracuda156** [comment]
@Matias314 Should be fixed now. I also tried to disable opportunistic stuff and added variants.

**Comment by Matias314** [comment]
It seems that PAM doesn't work on 10.5, configure fails now:
```
checking for crypt... yes
checking for security/pam_appl.h... no
configure: error: required helper auth/basic/PAM ... found but cannot be built
Command failed:  cd "/opt/local/var/macports/build/squid-c1397c4c/work/squid-7.5" && ./configure --prefix=/opt/local --datadir=/opt/local/share/squid --disable-arch-native --disable-strict-error-checking --enable-auth --enable-auth-basic=DB,NCSA,PAM,POP3,RADIUS,fake,getpwnam --enable-auth-digest=file --enable-auth-negotiate="wrapper" --enable-auth-ntlm --enable-delay-pools --enable-external-acl-helpers=delayer,file_userip,unix_group --enable-follow-x-forwarded-for --enable-log-daemon-helpers --enable-removal-policies --enable-storeio=ufs,aufs,diskd,rock --enable-zph-qos --libexecdir=/opt/local/libexec/squid --localstatedir=/opt/local/var/squid --mandir=/opt/local/share/man --sysconfdir=/opt/local/etc/squid --with-default-user=squid --with-ltdl-include=/opt/local/include --with-ltdl-lib=/opt/local/lib --with-pidfile=/opt/local/var/run/squid/squid.pid --with-swapdir=/opt/local/var/squid/cache --without-cppunit --without-gnutls --without-gss --without-heimdal-krb5 --without-ldap --without-mit-krb5 --without-nettle --with-openssl=/opt/local --without-sasl --without-tdb --without-xml2 --disable-eui 
Exit code: 1
Error: Failed to configure squid: consult /opt/local/var/macports/build/squid-c1397c4c/work/squid-7.5/config.log
Error: Failed to configure squid: configure failure: command execution failed
DEBUG: Error code: NONE
DEBUG: Backtrace: configure failure: command execution failed
```

**Comment by barracuda156** [comment]
Is it the only thing to exclude from defaults on 10.5?

**Comment by Matias314** [comment]
> Is it the only thing to exclude from defaults on 10.5?

Yes. Thank you for the quick fix, it works now!
